os:       linux
dist:     bionic
language: minimal

before_install:
    # build dependencies
    - sudo apt-get install -y tcl tcl-dev libglib2.0-0 libglib2.0-dev pkg-config libpcl1 libpcl1-dev iverilog
    # ubuntu does not provide pkg-config file for tcl...
    - 'sudo bash -c ''echo -e "Name: Tool Command Language\nDescription: Tcl\nVersion: 8.6\nLibs: -ltcl8.6 -ltclstub8.6\nCflags: -I/usr/include/tcl8.6" > /usr/share/pkgconfig/tcl.pc'''

script:
    - make -j3
    - make -j3 test
